### ISSUE TITLE
Hexo 7.0.0 Support (Throws Error)

### ISSUE THREAD

**Issue by kristofzerbe** [0ojixueseno0/hexo-info-api#2]
I have updated Hexo to 7.0.0 and had to uninstall **hexo-info-api**, because it throws following error:

```
TypeError: locals.categories.data.forEach is not a function
    at Hexo.module.exports (D:\OneDrive\Projekte\kiko.io\node_modules\hexo-info-api\lib\api\getPostsByCategory.js:16:28)
    at Hexo.tryCatcher (D:\OneDrive\Projekte\kiko.io\node_modules\hexo\node_modules\bluebird\js\release\util.js:16:23)
    at Hexo.<anonymous> (D:\OneDrive\Projekte\kiko.io\node_modules\hexo\node_modules\bluebird\js\release\method.js:15:34)
    at D:\OneDrive\Projekte\kiko.io\node_modules\hexo\dist\hexo\index.js:333:28
    at tryCatcher (D:\OneDrive\Projekte\kiko.io\node_modules\hexo\node_modules\bluebird\js\release\util.js:16:23)
    at MappingPromiseArray._promiseFulfilled (D:\OneDrive\Projekte\kiko.io\node_modules\hexo\node_modules\bluebird\js\release\map.js:68:38)
    at MappingPromiseArray.PromiseArray._iterate (D:\OneDrive\Projekte\kiko.io\node_modules\hexo\node_modules\bluebird\js\release\promise_array.js:115:31)
    at MappingPromiseArray.init (D:\OneDrive\Projekte\kiko.io\node_modules\hexo\node_modules\bluebird\js\release\promise_array.js:79:10)
    at MappingPromiseArray._asyncInit (D:\OneDrive\Projekte\kiko.io\node_modules\hexo\node_modules\bluebird\js\release\map.js:37:10)
    at _drainQueueStep (D:\OneDrive\Projekte\kiko.io\node_modules\hexo\node_modules\bluebird\js\release\async.js:97:12)
    at _drainQueue (D:\OneDrive\Projekte\kiko.io\node_modules\hexo\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (D:\OneDrive\Projekte\kiko.io\node_modules\hexo\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (D:\OneDrive\Projekte\kiko.io\node_modules\hexo\node_modules\bluebird\js\release\async.js:15:14)
    at processImmediate (node:internal/timers:464:21)
```

**Comment by jz0ojiang** [comment]
Done with https://github.com/jz0ojiang/hexo-info-api/commit/c38846829d12d25872b4b29cfff5eeabc38c0116
