### ISSUE TITLE
Cannot generate getCategories and getTags

### ISSUE THREAD

**Issue by wherewhere** [0ojixueseno0/hexo-info-api#3]
When enable `getCategories` or `getTags`, it report:
```
TypeError: Converting circular structure to JSON
    --> starting at object with constructor '_Document'
    |     property 'tags' -> object with constructor '_Query'
    |     property 'data' -> object with constructor 'Array'
    |     ...
    |     property 'data' -> object with constructor 'Array'
    --- index 0 closes the circle
    at JSON.stringify (<anonymous>)
    at module.exports (C:\Users\qq251\Downloads\Github\wherewhere.github.io\node_modules\hexo-info-api\lib\api\getCategories.js:9:20)
    at Hexo.<anonymous> (C:\Users\qq251\Downloads\Github\wherewhere.github.io\node_modules\hexo-info-api\index.js:38:20)
    at Hexo.tryCatcher (C:\Users\qq251\Downloads\Github\wherewhere.github.io\node_modules\bluebird\js\release\util.js:16:23)
    at Hexo.<anonymous> (C:\Users\qq251\Downloads\Github\wherewhere.github.io\node_modules\bluebird\js\release\method.js:15:34)
    at C:\Users\qq251\Downloads\Github\wherewhere.github.io\node_modules\hexo\dist\hexo\index.js:340:28
    at tryCatcher (C:\Users\qq251\Downloads\Github\wherewhere.github.io\node_modules\bluebird\js\release\util.js:16:23)
    at MappingPromiseArray._promiseFulfilled (C:\Users\qq251\Downloads\Github\wherewhere.github.io\node_modules\bluebird\js\release\map.js:68:38)
    at PromiseArray._iterate (C:\Users\qq251\Downloads\Github\wherewhere.github.io\node_modules\bluebird\js\release\promise_array.js:115:31)
    at MappingPromiseArray.init (C:\Users\qq251\Downloads\Github\wherewhere.github.io\node_modules\bluebird\js\release\promise_array.js:79:10)
    at MappingPromiseArray._asyncInit (C:\Users\qq251\Downloads\Github\wherewhere.github.io\node_modules\bluebird\js\release\map.js:37:10)
    at _drainQueueStep (C:\Users\qq251\Downloads\Github\wherewhere.github.io\node_modules\bluebird\js\release\async.js:97:12)
    at _drainQueue (C:\Users\qq251\Downloads\Github\wherewhere.github.io\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (C:\Users\qq251\Downloads\Github\wherewhere.github.io\node_modules\bluebird\js\release\async.js:102:5)
    at Async.drainQueues [as _onImmediate] (C:\Users\qq251\Downloads\Github\wherewhere.github.io\node_modules\bluebird\js\release\async.js:15:14)
    at process.processImmediate (node:internal/timers:478:21)
```
And the generated file of `getPostsByCategory`, `getPostsByCategoryId`, `getPostsByTag` and `getPostsByTagId` are empty.
```json
{"type":"getPostsByCategory","data":[]}
```
dependencies:
```json
"dependencies": {
  "hexo": "^7.0.0",
  "hexo-generator-archive": "^2.0.0",
  "hexo-generator-category": "^2.0.0",
  "hexo-generator-feed": "^3.0.0",
  "hexo-generator-index": "^3.0.0",
  "hexo-generator-robotstxt": "^0.2.0",
  "hexo-generator-searchdb": "^1.0.0",
  "hexo-generator-sitemap": "^3.0.0",
  "hexo-generator-tag": "^2.0.0",
  "hexo-info-api": "^0.2.0",
  "hexo-related-posts": "^1.0.0",
  "hexo-renderer-ejs": "^2.0.0",
  "hexo-renderer-marked": "^6.0.0",
  "hexo-renderer-stylus": "^3.0.0",
  "hexo-server": "^3.0.0",
  "hexo-theme-next": "^8.0.0",
  "hexo-util": "^3.0.0"
}
```

**Comment by jz0ojiang** [comment]
Hello! Thank you for submitting the issue.

Starting from version 0.2.0, hexo-info-api is compatible with hexo version 7.1.1 in https://github.com/jz0ojiang/hexo-info-api/commit/a49efa79e694d8945fd1e0daed02d52ea50af992.

The latest version of Hexo has undergone several changes to its variables. If you are using an older version of Hexo, please downgrade hexo-info-api to the previous version for compatibility.

**Comment by wherewhere** [comment]
```json
{
  "name": "wherlog",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "build": "hexo generate",
    "clean": "hexo clean",
    "deploy": "hexo deploy",
    "server": "hexo server"
  },
  "hexo": {
    "version": "7.2.0"
  },
  "dependencies": {
    "hexo": "^7.0.0",
    "hexo-generator-archive": "^2.0.0",
    "hexo-generator-category": "^2.0.0",
    "hexo-generator-feed": "^3.0.0",
    "hexo-generator-index": "^3.0.0",
    "hexo-generator-robotstxt": "^0.2.0",
    "hexo-generator-searchdb": "^1.0.0",
    "hexo-generator-sitemap": "^3.0.0",
    "hexo-generator-tag": "^2.0.0",
    "hexo-info-api": "^0.2.0",
    "hexo-related-posts": "^1.0.0",
    "hexo-renderer-ejs": "^2.0.0",
    "hexo-renderer-marked": "^6.0.0",
    "hexo-renderer-stylus": "^3.0.0",
    "hexo-server": "^3.0.0",
    "hexo-theme-next": "^8.0.0",
    "hexo-util": "^3.0.0"
  }
}
```
